### ISSUE TITLE
Alternative flow

### ISSUE THREAD

**Issue by damin8** [fancuk/ASAP#12]
-  대화의 대안 흐름!! (매우 중요)
-  1 : N (N>=1)
- 여러가지 세세하게
- 다들 생각나는 대로 여기다가 기록하기

**Comment by sg05138** [comment]
## **<1:1 일 경우>**
### **1.  채팅방 열기**
(정상흐름)
- 친구목록에서 대화상대 ID 더블클릭 / 1:1 대화목록 페이지에서 채팅방 더블클릭 => 채팅방 show

(대안흐름)
- 더블클릭 시 네트워크 또는 서버의 오류 => error message box show, 채팅방 생성X

### **2. 대화 전송**
(정상흐름)
- 채팅방 생성 시 하단의 대화 입력 box에 대화 입력 후 send button (대화상대 접속/비접속/부재중 시)
=> 채팅방 화면에 수신메세지는 오른쪽에, 송신메세지는 왼쪽에 기록

(대안흐름)
- 공백문자(null, space, enter) 입력 후 send button => '대화 내용을 입력하세요' message box show
- 서버 또는 네트워크 오류 => error message box show => 메세지 전송X
- 짧은 시간에 연속 메세지를 보낼 경우 => 

(정상흐름)
- 채팅방 생성 시 하단의 대화 입력 box에 대화 입력 후 asap button (대화 상대 접속 시)
=> 채팅방 화면 오른쪽에 대화내용 표시됨
- 송신자가 asap message를 10초 안에 볼 경우 메세지 내용 보여줌
- 송신자가 asap message를 보지 못 할 경우 10초 후에 사라짐

(대안흐름)
- 공백문자(null, space, enter) 입력 후 asap button => '대화 내용을 입력하세요' message box show
- 서버 또는 네트워크 오류 => error message box show => 메세지 전송X
- 짧은 시간에 연속 메세지를 보낼 경우 => 
- 상대방이 부재중 또는 비접속 시 일 경우 => '상대방이 비접속 or 부재중 이므로 asap 수신 불가' message box show
